plugins {
  alias libs.plugins.protobuf
}

dependencies {
  api libs.protobuf.java
}

tasks.named('jar') {
  duplicatesStrategy = DuplicatesStrategy.EXCLUDE
  from sourceSets.main.allJava
  from('src/main/java') {
    include '**/*.gwt.xml'
  }
}

sourceSets {
  main {
    java {
      srcDir "$buildDir/generated/source/proto/main/java"
    }
  }
}

protobuf {
  protoc {
    artifact = "com.google.protobuf:protoc:3.21.12"
  }
  generateProtoTasks {
    all().configureEach { task ->
      task.builtins {
        java {}
      }
    }
  }
}
