plugins {
  id 'java-library'
}

java {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_8
}

dependencies {
  api project(':client')
  implementation libs.commons.io
  implementation libs.netty.buffer
  implementation libs.netty.codec
  implementation libs.netty.transport

  testImplementation libs.junit
}
